services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend.dev

    working_dir: /app

    command: sh -c "npx prisma migrate deploy && npm run test && npm run build"

    depends_on:
      - postgres

    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/app_db
      JWT_SECRET: mysecret
  postgres:
    image: postgres:16

  #REFACTOR | EXAMPLE CREDENTIALS
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/app_db
      JWT_SECRET: mysecret